name: Run lint

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    run-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v5
              with:
                  node-version: 24
            - name: Prepare runtime directory
              run: sudo install -d -o "$USER" /captain
            - run: npm ci
            - run: npm run lint
            - run: npm run test:all
