name: Build and push the edge image

on:
    push:
        branches:
            - master

jobs:
    run-pre-checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v5
              with:
                  node-version: 24
            - name: Prepare runtime directory
              run: sudo install -d -o "$USER" /captain
            - run: npm ci
            - run: npm run build
            - run: npm run lint
            - run: npm run formatter
            - run: npm run test:all
    build-publish-docker-hub:
        needs: run-pre-checks
        runs-on: ubuntu-latest
        steps:
            - uses: azure/docker-login@v1
              with:
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}
            - uses: actions/checkout@v4
            - name: Build and Push Edge to DockerHub
              shell: bash
              run: ./dev-scripts/build_and_push_edge.sh
